export const FETCH_CAFES_REQUEST = "FETCH_CAFES_REQUEST";
export const FETCH_CAFES_SUCCESS = "FETCH_CAFES_SUCCESS";
export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
