export const FETCH_CAFES_REQUEST = "FETCH_CAFES_REQUEST";
export const FETCH_CAFES_SUCCESS = "FETCH_CAFES_SUCCESS";
export const FETCH_CAFES_FAILURE = "FETCH_CAFES_FAILURE";

export const CREATE_CAFE_REQUEST = "CREATE_CAFE_REQUEST";
export const CREATE_CAFE_SUCCESS = "CREATE_CAFE_SUCCESS";
export const CREATE_CAFE_FAILURE = "CREATE_CAFE_FAILURE";

export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
