export const FETCH_CAFES_REQUEST = "FETCH_CAFES_REQUEST";
export const FETCH_CAFES_SUCCESS = "FETCH_CAFES_SUCCESS";
export const FETCH_CAFES_FAILURE = "FETCH_CAFES_FAILURE";

export const CREATE_CAFE_REQUEST = "CREATE_CAFE_REQUEST";
export const CREATE_CAFE_SUCCESS = "CREATE_CAFE_SUCCESS";
export const CREATE_CAFE_FAILURE = "CREATE_CAFE_FAILURE";

export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE = "FETCH_EMPLOYEES_FAILURE";

export const FETCH_EMPLOYEES_WITH_CAFE_REQUEST =
  "FETCH_EMPLOYEES_WITH_CAFE_REQUEST";
export const FETCH_EMPLOYEES_WITH_CAFE_SUCCESS =
  "FETCH_EMPLOYEES_WITH_CAFE_SUCCESS";
export const FETCH_EMPLOYEES_WITH_CAFE_FAILURE =
  "FETCH_EMPLOYEES_WITH_CAFE_FAILURE";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";
