name: Log Traffic Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get traffic data
      run: |
        curl -H "Authorization: token ${{ secrets.LOG_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/traffic/views > traffic_data.json

    - name: Commit traffic data
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add traffic_data.json
        git commit -m "Update traffic data"
        git push
